db:
  username: postgres
  password: root
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 1
    last: 2
    key: value
  pool:
    size: 10
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20
    - size: 10
      timeout: 20

logging:
  level:
    root: WARN
    by.javagur.spring.database.repository.pool: INFO
  file:
    name: by.javaguru
    path: /logs/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: groot
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: update
